# Generated by Django 3.0.3 on 2021-01-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('briefing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=32)),
                ('date_create', models.DateField(editable=False)),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='briefing.Briefing')),
            ],
        ),
        migrations.CreateModel(
            name='Text_Ans',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Question')),
                ('ans', models.TextField()),
            ],
            bases=('question.question',),
        ),
        migrations.CreateModel(
            name='Variant_Ans',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Question')),
            ],
            bases=('question.question',),
        ),
    ]
