# Generated by Django 3.0.3 on 2021-01-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_variant_ans_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant_ans',
            name='is_oneVar',
            field=models.BooleanField(default=False, verbose_name='Ответ-один вариант'),
        ),
    ]
