# Generated by Django 3.0.3 on 2021-01-10 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_variant_ans_is_onevar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
