# Generated by Django 3.0.3 on 2021-01-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_usualuser_repeat_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usualuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
