# Generated by Django 3.0.3 on 2021-01-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210107_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usualuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
