# Generated by Django 3.0.3 on 2021-01-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.TextField()),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
            ],
            options={
                'permissions': (('find', 'can find any briefing'), ('answer', 'can answer on any briefing')),
            },
        ),
    ]
