# Generated by Django 3.0.3 on 2021-01-05 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('briefing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='who_respond',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
