# Generated by Django 3.0.3 on 2021-01-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0002_briefing_who_respond'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
