# Generated by Django 3.0.3 on 2021-01-07 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0003_briefing_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='briefing',
            options={'permissions': (('briefing.find_briefing', 'can find any briefing'), ('briefing.answer_briefing', 'can answer on any briefing'))},
        ),
    ]
