# Generated by Django 3.0.3 on 2021-01-07 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0004_auto_20210108_0447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='briefing',
            options={'permissions': (('briefing.find', 'can find any briefing'), ('briefing.answer', 'can answer on any briefing'))},
        ),
    ]
