# Generated by Django 3.0.3 on 2021-01-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0005_auto_20210108_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='briefing',
            options={'permissions': (('find_briefing', 'can find any briefing'), ('answer_briefing', 'can answer on any briefing'))},
        ),
    ]
