# Generated by Django 3.0.3 on 2021-01-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0007_auto_20210121_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='briefing',
            options={},
        ),
    ]
